- app/src/main/java/ani/saikou/manga/source/MangaReaderTransformation.kt
just do 
```
Glide.with(...)
.load(url)
.transformMangaReader()
.into(...)
```
> Added util to deobfuscate mangareader pages

- app/src/main/java/ani/saikou/manga/source/parsers/MangaReaderToTransformation.kt
this should work on all images provided you use transformMangaReader()
> fixed all image sizes

- app/src/main/java/ani/saikou/manga/source/parsers/MangaReaderToTransformation.kt
this ought to be the final fix
> fixed large images

- app/src/main/AndroidManifest.xml
- app/src/main/java/ani/saikou/anime/ExoplayerView.kt
- app/src/main/res/drawable/ic_baseline_picture_in_picture_24.xml
- app/src/main/res/layout/exo_styled_player_control_view.xml
> PiP Support

- app/src/main/java/ani/saikou/manga/source/parsers/MangaKakaLot.kt
> Mangakakalot: Fix Title Not Showing Sometimes

- app/src/main/java/ani/saikou/AnimePageAdapter.kt
- app/src/main/java/ani/saikou/HomeFragment.kt
- app/src/main/java/ani/saikou/MangaPageAdapter.kt
:x:: ![temp](https://user-images.githubusercontent.com/27722281/163141713-13af70c4-6f7b-48bc-8fda-5f2f9ca48dad.jpg)
:white_check_mark:: ![image](https://user-images.githubusercontent.com/27722281/163141862-5a9c2da1-ea73-4321-a2a8-eb7d41f18bea.png)
(edited, sorry)
> fixed avatar in round

- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/kotlinScripting.xml
> Add formatter rules

- app/src/main/java/ani/saikou/anilist/AnilistQueries.kt
- app/src/main/java/ani/saikou/media/Media.kt
Fixed an issue where user lists were not being sorted by updatedAt when having that option in Anilist
> Fixed sort by last updated in user lists

- app/src/main/java/ani/saikou/parsers/MangaSources.kt
- app/src/main/java/ani/saikou/parsers/anime/AllAnime.kt
- app/src/main/java/ani/saikou/parsers/manga/AllAnime.kt
Also a very very slight addition to the anime side
Couldn't find issues with my library, though I do not read as much as I watch
> AllAnime: Add Manga

- app/src/main/java/ani/saikou/parsers/anime/AllAnime.kt
- app/src/main/java/ani/saikou/parsers/manga/AllAnime.kt
> Fix AllAnime++

- app/src/main/java/ani/saikou/parsers/anime/NineAnime.kt
- app/src/main/java/ani/saikou/parsers/anime/extractors/VidVard.kt
This correctly translates the link in the gist, but fails with "Source Error" so that needs investigating before merging
> Add VideoVard

- .github/workflows/pull-req.yml
Updated workflow to not run unnecessarily
> Update pull-req workflow

- .github/ISSUE_TEMPLATE/config.yml
I'm using the URL which is in the readme, hopefully it doesn't change.
> Add proper Discord url

- README.md
- app/src/main/java/ani/saikou/parsers/MangaSources.kt
Nhentai has removed its cloudfare protection for a few weeks now. Looks like it's alright to add it back.
> Re-add nhentai source

- .github/ISSUE_TEMPLATE/bug_report.yml
- app/src/main/java/ani/saikou/settings/SettingsActivity.kt
Lets users to copy few information of their device from settings. Useful for submitting a bug report.
https://user-images.githubusercontent.com/70033559/174475649-037fe50b-2660-41bb-a1d3-c07cc9dde4f0.mp4
> Add device info

- README.md
- app/src/main/java/ani/saikou/parsers/MangaSources.kt
- app/src/main/java/ani/saikou/parsers/manga/Comickfun.kt
~~This is still work in progress. I have only tested a limited number of mangas. Once GitHub Actions has built the APK, and if anyone wants to help me find bugs, please do so by reporting it here.~~
I have tested this and so far haven't found any issues. Should be good to merge.
> Add Comickfun manga source

- app/src/main/java/ani/saikou/parsers/manga/Comickfun.kt
Fixed to not find `buildId` every time when loading a chapter.
Fixed an issue with incorrect regex.
> Refactor Comickfun

- app/src/main/java/ani/saikou/parsers/MangaSources.kt
- app/src/main/java/ani/saikou/parsers/manga/MangaHub.kt
Still WIP. Need to test some more and also do some clean up.
> Add MangaHub manga source

- app/src/main/java/ani/saikou/parsers/MangaSources.kt
- app/src/main/java/ani/saikou/parsers/manga/MangaKatana.kt
> Add MangaKatana manga source

- app/src/main/java/ani/saikou/anime/ExoplayerView.kt
- app/src/main/java/ani/saikou/settings/PlayerSettings.kt
- app/src/main/java/ani/saikou/settings/PlayerSettingsActivity.kt
- app/src/main/res/layout/activity_player_settings.xml
- app/src/main/res/values/strings.xml
Adds the option to choose the default resize mode to the player settings
> feat: Default Resize Mode

- app/src/main/java/ani/saikou/anime/ExoplayerView.kt
- app/src/main/java/ani/saikou/settings/PlayerSettings.kt
- app/src/main/java/ani/saikou/settings/PlayerSettingsActivity.kt
- app/src/main/res/drawable/ic_round_color_24.xml
- app/src/main/res/drawable/ic_round_format_text_24.xml
- app/src/main/res/layout/activity_player_settings.xml
- app/src/main/res/values/strings.xml
Added options to change Subtitle
- Primary Color
- Outline Color
- Outline type
This currently only works with sources that have video and subtitles seperate, but I think this might be useful, should the player ever be usable with downloaded files.
> Added options to customize subtitles

- app/src/main/java/ani/saikou/anime/ExoplayerView.kt
- app/src/main/java/ani/saikou/settings/PlayerSettings.kt
- app/src/main/java/ani/saikou/settings/PlayerSettingsActivity.kt
- app/src/main/res/drawable/ic_round_font_size_24.xml
- app/src/main/res/layout/activity_player_settings.xml
- app/src/main/res/values/strings.xml
Added a textfield to change subtitle font size to player settings.
> Change subtitle font size

- app/src/main/java/ani/saikou/anime/ExoplayerView.kt
- app/src/main/java/ani/saikou/others/ResettableTimer.kt
Added functionality to fast rewind/forward in an episode in values multiples of the seekTime (eg 10, 20, 30...). It was just really bugging me so I decided to fix it. Skipping many times should be more consistent now. This is a first implementation so it is a little rough if any style or code changes should be made please let me know. :)
Preview:
PS: This has 4, 10 second increments.
> Add incremental seek functionality

- app/src/main/java/ani/saikou/anime/ExoplayerView.kt
this fixes a bug that happens when you quickly seek in the opposite direction of the seek before it, getting the animation stuck
to fix it, I added separate timers and seekTimes(for the text) and resetting them separate
also new (as a side effect): seeking into both directions at once!
> fixed seek animation getting stuck

- app/src/main/java/ani/saikou/parsers/anime/Kamyroll.kt
- app/src/main/res/layout/activity_player_settings.xml
- app/src/main/res/values/strings.xml
change: changed some strings to better match current functionality
change: server select when using Kamyroll shows language alongside locale code
change: moved Kamyroll locale select button to "Other" in player settings
> Modified a few thing around Kamyroll

- app/src/main/java/ani/saikou/anime/ExoplayerView.kt
- app/src/main/java/ani/saikou/anime/SubtitleDialogFragment.kt
change: subtitle dialog fragment entries now with long language name
feat: exo player and subtitle dialog now save/load last selected subtitle language on a per-anime basis
> Subtitle Dialog Fragment Changes

- app/src/main/java/ani/saikou/anime/ExoplayerView.kt
- app/src/main/java/ani/saikou/anime/SubtitleDialogFragment.kt
- app/src/main/java/ani/saikou/parsers/anime/Kamyroll.kt
- app/src/main/java/ani/saikou/settings/PlayerSettings.kt
- app/src/main/java/ani/saikou/settings/PlayerSettingsActivity.kt
- app/src/main/res/drawable/ic_round_alpha_t_box_24.xml
- app/src/main/res/layout/activity_player_settings.xml
- app/src/main/res/values/strings.xml
This pr aims to update the Kamyroll parser to use the newest version of the Kamyroll API
> feat: update Kamyroll parser to use newest api & hostserver
